version: '3.9'
name: 'last_hackaton'

volumes:
  static_volume:
  media_volume:
  pg_data:
  redoc:

networks:
  backend:

services:
  db:
    image: postgres:13.10
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data
    hostname: localhost
    restart: unless-stopped
  backend:
#    image: amir800s/last_hackaton_backend
    build: ../backend/
    restart: always
    env_file: .env
    volumes:
      - static_volume:/app/static/
      - media_volume:/app/media/
  nginx:
#    image: nginx:1.22.1
    build: .
    env_file: .env
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/
      - static_volume:/var/html/static/
      - media_volume:/var/html/media/
    ports:
      - '80:80'